platform :ios, '8.0'

source  "https://github.com/CocoaPods/Specs.git"

inhibit_all_warnings!

target 'CYInstanceDebugHook' do
    pod 'CYToolkit',  :git => 'https://github.com/chrisYooh/CYToolkit.git', :commit => 'b3a7c09'
end
